// manager.c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "timerIDL.h" // header file generated by rpcgen

int requestTime = 0;
// get the average time from an array of long values
long get_average_time(long times[], int n) {
    long sum = 0;
    for (int i = 0; i < n; i++) {
        sum += times[i];
    }
    return sum / n;
}

int main(int argc, char *argv[]) {
    if (argc <= 1) {
        return 0;
    }
    // get the number of workers from the arguments
    int num_workers = argc - 1;

    // create an array of client handles for each worker
    CLIENT *workers[num_workers];
    for (int i = 0; i < num_workers; i++) {
        workers[i] = clnt_create(argv[i + 1], TIMER_PROG, TIME_VERS, "udp");
        if (workers[i] == NULL) {
            clnt_pcreateerror(argv[i + 1]);
            exit(1);
        }
    }

    // loop forever
    while (1) {
        // create an array of long values for each worker
        requestTime += 1;
        long times[num_workers];
        // get the time from each worker using RPC
        for (int i = 0; i < num_workers; i++) {
            long *result = get_time_1(NULL, workers[i]);
            if (result == NULL) {
                clnt_perror(workers[i], "get_time");
                exit(1);
            }
            times[i] = *result;
            printf("Time from worker %s: %ld\n", argv[i+1], times[i]);
        }
        // calculate the average time
        long avg = get_average_time(times, num_workers);
        printf("Average time: %ld\n", avg);
        // send the average time to each worker using RPC
        for (int i = 0; i < num_workers; i++) {
            void *result = set_time_1(&avg, workers[i]);
            if (result == NULL) {
                clnt_perror(workers[i], "set_time");
                exit(1);
            }
        }
        // wait for the next interval
        sleep(INTERVAL);
    }
    return 0;

}
