/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "timerIDL.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <time.h>
#include <pthread.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
timer_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		long set_time_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_TIME:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_long;
		local = (char *(*)(char *, struct svc_req *)) get_time_1_svc;
		break;

	case SET_TIME:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) set_time_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

// Mutex for synchronizing access to the local clock
pthread_mutex_t clock_mutex = PTHREAD_MUTEX_INITIALIZER;
int local_clock;
// Function to update the local clock with a random integer
void* update_local_clock(void* arg) {
    while (1) {
        // Use a mutex to protect the critical section (updating the local clock)
        pthread_mutex_lock(&clock_mutex);
        
        // Update the local clock with a random integer
        local_clock += rand() % 10;
        // Release the mutex
        pthread_mutex_unlock(&clock_mutex);
        // Sleep for a while before updating again
        sleep(INTERVAL);  // You can adjust the sleep duration as needed
    }
    return NULL;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TIMER_PROG, TIME_VERS);

	srand(time(NULL));

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TIMER_PROG, TIME_VERS, timer_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TIMER_PROG, TIME_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TIMER_PROG, TIME_VERS, timer_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TIMER_PROG, TIME_VERS, tcp).");
		exit(1);
	}
    
    // Start a thread for updating the local clock
    pthread_t clock_thread;
    if (pthread_create(&clock_thread, NULL, update_local_clock, NULL) != 0) {
        fprintf(stderr, "%s", "Error creating clock thread.\n");
        exit(1);
    }

	svc_run ();

    // Cleanup: Join the clock thread when the program exits
    if (pthread_join(clock_thread, NULL) != 0) {
        fprintf(stderr, "%s", "Error joining clock thread.\n");
        exit(1);
    }

	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
