// worker.c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "timerIDL.h" // header file generated by rpcgen
extern 
// global variable to store the local clock
long local_time = 0;

// service function to get the time from the worker
long *get_time_1_svc(void *argp, struct svc_req *rqstp) {
    // allocate memory for the result
    static long result;
    // update the local clock randomly
    local_time += rand() % 10;
    // set the result to the local clock
    result = local_time;
    // return a pointer to the result
    return &result;
}

// service function to set the time to the worker
void *set_time_1_svc(long *argp, struct svc_req *rqstp) {
    // allocate memory for the result
    static char *result;
    // get the average time from the argument
    long avg_time = *argp;
    // display the average time
    printf("Average time: %ld\n", avg_time);
    // return a pointer to the result
    return (void *)&result;
}

int main(int argc, char *argv[]) {
    // create a UDP socket
    int sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock < 0) {
        perror("socket");
        exit(1);
    }
    // bind the socket to port 8000
    struct sockaddr_in addr;
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(1245);
    if (bind(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind");
        exit(1);
    }
    // create a service handle using svcudp_create
    SVCXPRT *transp = svcudp_create(sock);
    if (transp == NULL) {
        fprintf(stderr, "svcudp_create failed\n");
        exit(1);
    }
    // register the service functions with the RPC runtime
    if (!svc_register(transp, TIMER_PROG, TIME_VERS, timer_prog_1, IPPROTO_UDP)) {
        fprintf(stderr, "svc_register failed\n");
        exit(1);
    }
    // loop forever
    svc_run();
    return 0;
}
